name: Check compatibility

on:
  pull_request

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Notify about compatibility check
        uses: peter-evans/create-or-update-comment@v4
        id: notification
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ⚠️ Checking compatibility on this PR ⚠️

      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17
          settings-pluginRepositories: '[{"id":"nbbrd-snapshots","name":"nbbrd-snapshots","url":"https://s01.oss.sonatype.org/content/repositories/snapshots","snapshots":{"enabled":true}}]'

      - name: Check compatibility on PR
        run: mvn -U verify -D skipTests -P check-downstream

      - name: Replace notification with compatibility report
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.notification.outputs.comment-id }}
          body-path: 'target/compatibility.md'
          edit-mode: replace
