name: Check main on JD+ develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-main-job:
    strategy:
      fail-fast: false
      matrix:
        plugin:
#          - 'jdemetra/jdplus-benchmarking'
          - 'jdemetra/jdplus-incubator'
#          - 'jdemetra/jdplus-experimental'
#          - 'jdemetra/jdplus-revisions'
#          - 'jdemetra/jdplus-nowcasting'
#          - 'nbbrd/jdplus-sdmx'
        version: [ 3.2.4, 3.3.0, 3.4.0, 3.4.1-SNAPSHOT ]

    name: ${{matrix.plugin}}@${{matrix.version}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17

      - name: Checkout plugin
        run: git clone https://github.com/${{matrix.plugin}} plugin -b main --single-branch

      - name: Output plugin version
        run: mvn -f plugin/pom.xml  help:evaluate -Dexpression=project.version -q -DforceStdout >> $GITHUB_STEP_SUMMARY

      - name: Output JD+ version
        run: mvn -f plugin/pom.xml  help:evaluate -Dexpression=project.version -q -DforceStdout >> $GITHUB_STEP_SUMMARY

      - name: Set JD+ version
        run: mvn -f plugin/pom.xml versions:set-property -Dproperty=jdplus-main.version -DnewVersion=${{matrix.version}}

#      - name: Compile
#        id: compilation
#        run: |
#          set +e
#          version="$(echo ${{ matrix.version }} | jq -c --slurp .)"
#          mvn -f plugin/pom.xml clean install -U -DskipTests -Denforcer.skip
#          echo "exitcode_$version=$version" >> $GITHUB_OUTPUT

      - name: Create JSON file
        run: echo "${{matrix.plugin}}_${{matrix.version}}" > data.json
      - name: Create artifact name
        run: artifact_name=$(echo ${{matrix.plugin}}_${{matrix.version}} | tr "/" "_")
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: $artifact_name
          path: data.json

  gen-summary-job:
    runs-on: ubuntu-latest
    needs: check-main-job
    steps:
      - name: Download JSON artifact
        uses: actions/download-artifact@v4
#        with:
#          merge-multiple: true
      - run: ls -R
