name: Check main on JD+ develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-main-job:
    strategy:
      fail-fast: false
      matrix:
        plugin:
#          - 'jdemetra/jdplus-benchmarking'
          - 'jdemetra/jdplus-incubator'
#          - 'jdemetra/jdplus-experimental'
#          - 'jdemetra/jdplus-revisions'
#          - 'jdemetra/jdplus-nowcasting'
#          - 'nbbrd/jdplus-sdmx'
        version: [ 3.2.4, 3.3.0, 3.4.0, 3.4.1-SNAPSHOT ]

    name: ${{matrix.plugin}}@${{matrix.version}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17

      - name: Checkout plugin
        run: git clone https://github.com/${{matrix.plugin}} plugin -b main --single-branch

      - name: Gather and configure versions
        run: |
          plugin_version=$(mvn -f plugin/pom.xml  help:evaluate -Dexpression=project.version -q -DforceStdout)
          jdplus_version=$(mvn -f plugin/pom.xml  help:evaluate -Dexpression=jdplus-main.version -q -DforceStdout)
          mvn -f plugin/pom.xml versions:set-property -Dproperty=jdplus-main.version -DnewVersion=${{matrix.version}}

#      - name: Compile
#        id: compilation
#        run: |
#          set +e
#          version="$(echo ${{ matrix.version }} | jq -c --slurp .)"
#          mvn -f plugin/pom.xml clean install -U -DskipTests -Denforcer.skip
#          echo "exitcode_$version=$version" >> $GITHUB_OUTPUT

      - name: Create artifact name
        run: |
          echo "artifact_name=$(echo ${{matrix.plugin}}_${{matrix.version}} | tr "/" "_")" >> $GITHUB_ENV

      - name: Create report
        run: |
          echo '{"exitcode": 0, "plugin": "${{matrix.plugin}}", "version": "${{matrix.version}}", "plugin_version": "$plugin_version"}' > ${{ env.artifact_name }}.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_name }}.json

  gen-summary-job:
    runs-on: ubuntu-latest
    needs: check-main-job
    steps:
      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: echo $(jq -s *.json) >> $GITHUB_STEP_SUMMARY
