name: Check main on JD+ develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-main-job:
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - 'jdemetra/jdplus-benchmarking'
          - 'jdemetra/jdplus-incubator'
          - 'jdemetra/jdplus-experimental'
          - 'jdemetra/jdplus-revisions'
          - 'jdemetra/jdplus-nowcasting'
          - 'nbbrd/jdplus-sdmx'
        version: [ 3.3.0, 3.4.0, 3.4.1-SNAPSHOT ]

    name: ${{matrix.plugin}}/${{matrix.version}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 21

      - name: Checkout and compile
        run: | 
          git clone https://github.com/${{matrix.plugin}} plugin -b main --single-branch
          mvn versions:set-property -f plugin/pom.xml -Dproperty=jdplus-main.version -DnewVersion=${{matrix.version}}
          mvn clean install -DskipTests -Denforcer.skip -f plugin/pom.xml
