name: Check main on JD+ develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-main-job:
    strategy:
      fail-fast: false
      matrix:
        plugin:
          #          - 'jdemetra/jdplus-benchmarking'
          - 'jdemetra/jdplus-incubator'
        #          - 'jdemetra/jdplus-experimental'
        #          - 'jdemetra/jdplus-revisions'
        #          - 'jdemetra/jdplus-nowcasting'
        #          - 'nbbrd/jdplus-sdmx'
        version: [ 3.2.4, 3.3.0, 3.4.0, 3.4.1-SNAPSHOT ]

    name: ${{matrix.plugin}}@${{matrix.version}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17

      - name: Create artifact name
        run: |
          echo "artifact_name=$(echo ${{matrix.plugin}}_${{matrix.version}} | tr "/" "_")" >> $GITHUB_ENV

      - name: Setup and run compilation to create report
        run: |
          git clone https://github.com/${{matrix.plugin}} plugin
          pushd plugin
          set +e
          for i in $(git tag)
          do
            git checkout $i
            plugin_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            jdplus_version=$(mvn help:evaluate -Dexpression=jdplus-main.version -q -DforceStdout)
            mvn versions:set-property -Dproperty=jdplus-main.version -DnewVersion=${{matrix.version}}
            mvn clean verify -U -DskipTests -Denforcer.skip -q
            exitcode=$?
            echo "$exitcode,${{matrix.plugin}},${{matrix.version}},$plugin_version" >> ../${{ env.artifact_name }}.csv
            mvn clean -q
            git restore .
          done
          set -e
          popd

      - name: Print report
        run: cat ${{ env.artifact_name }}.csv

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.artifact_name }}.csv

  gen-summary-job:
    runs-on: ubuntu-latest
    needs: check-main-job
    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17

      - name: Download report
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - run: cat *.csv > data.csv

      - name: Generate summary
        run: mvn clean install

      - run: java -jar target/nbm_dashboard-1.0.0-SNAPSHOT-bin.jar data.csv > $GITHUB_STEP_SUMMARY
