name: Check compatibility

on:
  pull_request

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17
          settings-pluginRepositories: '[{"id":"nbbrd-snapshots","name":"nbbrd-snapshots","url":"https://s01.oss.sonatype.org/content/repositories/snapshots","snapshots":{"enabled":true}}]'

      - name: Check compatibility
        run: mvn -U verify -P check-downstream

      - name: Install fs resource
        run: npm install fs

      - name: Add report as comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fs.readFileSync('target/compatibility.md', 'utf8')
            })
            
