name: Check main on JD+ develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-main-job:
    strategy:
      fail-fast: false
      matrix:
        plugin:
#          - 'jdemetra/jdplus-benchmarking'
          - 'jdemetra/jdplus-incubator'
#          - 'jdemetra/jdplus-experimental'
#          - 'jdemetra/jdplus-revisions'
#          - 'jdemetra/jdplus-nowcasting'
#          - 'nbbrd/jdplus-sdmx'
        version: [ 3.2.4, 3.3.0, 3.4.0, 3.4.1-SNAPSHOT ]

    name: ${{matrix.plugin}}@${{matrix.version}}
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.compilation.outputs.exitcode }}

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17

      - name: Checkout plugin
        run: git clone https://github.com/${{matrix.plugin}} plugin -b main --single-branch

      - name: Output plugin version
        run: mvn -f plugin/pom.xml  help:evaluate -Dexpression=project.version -q -DforceStdout >> $GITHUB_STEP_SUMMARY

      - name: Output JD+ version
        run: mvn -f plugin/pom.xml  help:evaluate -Dexpression=project.version -q -DforceStdout >> $GITHUB_STEP_SUMMARY

      - name: Set JD+ version
        run: mvn -f plugin/pom.xml versions:set-property -Dproperty=jdplus-main.version -DnewVersion=${{matrix.version}}

      - name: Compile
        id: compilation
        run: |
          set +e
          version=${{ matrix.version }}
          mvn -f plugin/pom.xml clean install -U -DskipTests -Denforcer.skip
#          echo "exitcode=$?" >> $GITHUB_OUTPUT
          echo "exitcode=$version" >> $GITHUB_OUTPUT

  gen-summary-job:
    runs-on: ubuntu-latest
    needs: check-main-job
    steps:
      - run: echo '${{ toJSON(needs.check-main-job.outputs) }}'
