name: Check main on JD+ develop

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  check-main-job:
    strategy:
      fail-fast: false
      matrix:
        java: [ 21 ]
        os:
          - ubuntu-latest     # Linux x64

    name: JDK${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: ${{ matrix.java }}

      - name: Checkout and compile jdplus-main
        run: | 
          git clone https://github.com/jdemetra/jdplus-main
          mvn clean install -DskipTests -f jdplus-main/pom.xml -T1C

      - name: Checkout and compile jdplus-incubator
        run: | 
          git clone https://github.com/jdemetra/jdplus-incubator -b main --single-branch
          mvn versions:set-property -f jdplus-incubator/pom.xml -Dproperty=jdplus-main.version -DnewVersion=3.4.1-SNAPSHOT
          mvn clean install -DskipTests -f jdplus-incubator/pom.xml -T1C
