on:
  pull_request

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: 17

      - name: Check compatibility
        run: mvn -U validate -P check-downstream

      - name: Read report
        run: |
          cat target/compatibility.md >> $ABC
          echo "REPORT=$ABC" >> $GITHUB_ENV

      - name: Print report
        run: echo "${{env.REPORT}}"

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! \n ${{env.REPORT}}'
            })
            
